name: autorun

on:
  schedule:
    # 每天凌晨2点30分运行一次
    - cron: '30 2 * * *'

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run script on remote server
      run: ssh -o StrictHostKeyChecking=no dino@s4.serv00.com "screen -S vless node /home/liyizi2/domains/liyizi2.serv00.net/vless/app.js'"
#screen -S vless -dm bash -c 'node /home/liyizi2/domains/liyizi2.serv00.net/vless/app.js
